services:
    sylius.form.type.gateway_configuration.payzen:
        class: Antilop\SyliusPayzenBundle\Form\Type\PayzenGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: payzen, label: sylius.payzen_gateway_factory.payzen_checkout }
            - { name: form.type }

    sylius.payment.payzen.factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Antilop\SyliusPayzenBundle\PayzenGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: payzen }
    antilop.payment.payzen.factory:
        class: Antilop\SyliusPayzenBundle\Factory\PayzenClientFactory
        arguments: ['@sylius.repository.payment_method']

    antilop.payment.payzen.processor:
        class: Antilop\SyliusPayzenBundle\Processor\OrderPaymentProcessor
        decorates: sylius.order_processing.order_payment_processor.checkout
        arguments: ['@.inner', '@sm.factory', '@antilop.payment.payzen.factory']

    Antilop\SyliusPayzenBundle\EventListener\UpdateBankDetailListener:
        decorates: App\EventListener\Subscription\BankDetailListener
        arguments: ['@sm.factory']


